# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
  
- script: |
    npm install
  displayName: 'install'
  timeoutInMinutes: 5

- script: |
    npm i --no-save vue@2.6.11 vuetify@2.2.18
  displayName: 'install peerDependencies'
  timeoutInMinutes: 5

- script: |
    npm run build:lib
  displayName: 'build lib'
  timeoutInMinutes: 5

- script: |
    npm run build:storybook
  displayName: 'build storybook'
  timeoutInMinutes: 5

- task: Npm@1
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '53b96380-cf7f-4488-8b56-e55e5bf9131e/14726a35-0ff3-4e86-917b-0b9b4847343d'